### ISSUE TITLE
response class

### ISSUE THREAD

**Issue by nunogoncalves** [richhollis/swagger-docs-sample#1]
Hi,
I'm following swagger-docs to create documentation for a service I'm building. 
I was looking at the petStore example and saw a response class in the following request. 
http://petstore.swagger.wordnik.com/#!/pet/getPetById

This would be helpful. How can I create a response class? I was searching and can't find anything to help me with that. :)

**Comment by xytian315** [comment]
Did you find the answer? I am very interested to know this too. Thank you

**Comment by nunogoncalves** [comment]
yes. Using the keyword type.
Here's an example.

``` ruby

swagger_api :show do 
   param :path, 'id', :integer, :required, 'id of dog to fetch'
   type 'dog'
   response :unauthorized
   response :ok, "success"
end

swagger_model :dog do
....
end
```
